# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0357057875e7682a8fd1cf82715fe379cee578df41e27090105eb31d3d609ddfdbb5554f13b0d5039b5ad8a9c50558ce5c46a5c6cf2734e99a62c6704736d302

test:
  secret_key_base: 96a9d4446d2efd88fc037449b407034057a52ea9bf7e81fab7e1595d473434132a7b639235786665dd72780c8419cb6ec7c2248d00e8402f38c159d346da2280

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
